# Generated by Django 3.2.5 on 2021-07-24 10:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('filer', '0013_auto_20210724_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.CreateModel(
            name='RuTaggedItem',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taggit.taggeditem',),
        ),
        migrations.CreateModel(
            name='TbContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bContentPublish', models.BooleanField(db_index=True, default=True, help_text='Опубликованный контент будет отображаться в соответствующей ленте категории и&nbsp;при его просмотре будет отображаться навигация &laque;Предыдущий&raque; и&nbsp;&laque;Следующий&raque; по ленте. По прямому URL (если его знать) отображается даже не опубликованный контент (но без навигации).', verbose_name='Опуб…')),
                ('tdContentPublishUp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Дата публикации, с её момента новость появится на сайте.', verbose_name='Начало публикации')),
                ('tdContentPublishDown', models.DateTimeField(db_index=True, default=0, help_text='Дата окончания публикации, с её момента новость исчезнет с сайта.', verbose_name='Окончания публикации')),
                ('szContentHead', models.CharField(default='', help_text='Заголовок контента <small>(допустим HTML-код, будет обработан типографом, если его включить, максимальная длинна <b>512 символов</b>)</small>', max_length=512, verbose_name='Заголовок')),
                ('szContentIntro', ckeditor.fields.RichTextField(default='', help_text='Анонс <small>(допустим HTML-код, будет обработан типографом, если его включить)</small>', verbose_name='Анонс')),
                ('szContentBody', ckeditor.fields.RichTextField(default='', help_text='Содержание <b>БЕЗ АНОНСА</b> <small>(допустим HTML-код, будет обработан типографом, если его включить)</small>', verbose_name='Содержание')),
                ('szContentSlug', models.CharField(blank=True, default='', help_text='Слуг… 128 символов.<br /><small><b>Если оставить пустым, то slug сформируется автоматически</b></small>', max_length=128, null=True, verbose_name='Slug')),
                ('iContentHits', models.PositiveIntegerField(db_index=True, default=0, help_text='Число просмотров', verbose_name='◉')),
                ('bTypograf', models.BooleanField(default=False, help_text='Обработать через <a href="https://www.typograf.ru" target="_blank">Типограф 2.0</a><br /><small><b>НОРМАЛЬНЫЙ ТИПОГРАФ, ХОРОШИЙ HTML, РЕКОМЕНДУЕМ</b><br />&laquo;приклеивает&raquo; союзы, поддерживает неразрывные конструкции,<br />замена тире, кавычек и дефисов, расстановка &laquo;мягких переносов&raquo;<br />в словах длиннее 12 символов, убирает &laquo;вдовы&raquo; &laquo;сироты&raquo; (кроме<br />заголовков), расставляет абзацы (кроме заголовков), расшифро-<br />вывает аббревиатуры (те, что знает и кроме заголовков), висячая<br />пунктуация (только в заголовках) и т.п.</small>', verbose_name='Типограф Стандарт')),
                ('szContentKeywords', models.CharField(blank=True, default='', help_text='Ключевые слова. Через запятую. 256 символов.', max_length=256, null=True, verbose_name='Keywords (SEO)')),
                ('szContentDescription', models.CharField(blank=True, default='', help_text='Описание страницы… 256 символов (включая пробелы), но поисковики обработают только 155–160 из них.<br /><small><b>Если оставить пустым, то описание сформируется автоматически на базе заголовка и анонса</b></small>', max_length=256, null=True, verbose_name='Description (SEO)')),
                ('dtContentCreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('dtContentTimeStamp', models.DateTimeField(auto_now=True, verbose_name='Штамп времени')),
                ('imgContentPreview', filer.fields.file.FilerFileField(blank=True, help_text='Картинка-превью', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Превью', to='filer.file', verbose_name='Превью')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text="Теги через запятую… Регистр не чувствителен… Длинные теги, содержащие пробел, заключайте'в кавычки'… <b>Теги нужны для присвоения категорий объектам контента<b>.", through='web.RuTaggedItem', to='taggit.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['-tdContentPublishUp'],
            },
        ),
    ]
