# Generated by Django 3.2.5 on 2021-07-24 10:17
# C:\PYTHON\ENV\cadpoint2\lib\site-packages\easy_thumbnails\migrations\0003_auto_20210724_1317.py
#     - Alter field id on source
#     - Alter field id on thumbnail
#     - Alter field id on thumbnaildimensions


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_thumbnails', '0002_thumbnaildimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thumbnaildimensions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
