# Generated by Django 5.2.13 on 2026-04-09 12:21

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('web', '0001_squashed_0002_alter_tbcontent_szcontentbody_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcontent',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Теги можно выбирать из списка или вводить вручную. Многословные теги поддерживаются без кавычек. <b>Теги нужны для присвоения категорий объектам контента<b>.', through='web.RuTaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
