# Generated by Django 3.2.5 on 2021-08-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_tbcontent_tdcontentpublishdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcontent',
            name='bTypograf',
            field=models.BooleanField(default=False, help_text='Обработать через <a href="https://www.typograf.ru" target="_blank">Типограф 2.0</a><br /><small><b>НОРМАЛЬНЫЙ ТИПОГРАФ, ХОРОШИЙ HTML, РЕКОМЕНДУЕМ</b> &laquo;приклеивает&raquo; союзы, поддерживает неразрывные конструкции, замена тире, кавычек и дефисов, расстановка &laquo;мягких переносов&raquo; в словах длиннее 12 символов, убирает &laquo;вдовы&raquo; &laquo;сироты&raquo; (кроме заголовков), расставляет абзацы (кроме заголовков), расшифровывает аббревиатуры (те, что знает и кроме заголовков), висячая пунктуация (только в заголовках) и т.п.</small>', verbose_name='Типограф Стандарт'),
        ),
        migrations.AlterField(
            model_name='tbcontent',
            name='tdContentPublishDown',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Дата окончания публикации, с её момента новость исчезнет с сайта.', null=True, verbose_name='Окончания публикации'),
        ),
    ]
