# Generated by Django 5.2.13 on 2026-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('web', '0003_alter_tbcontent_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbcontent',
            name='bTypograf',
        ),
        migrations.AddIndex(
            model_name='tbcontent',
            index=models.Index(fields=['bContentPublish', 'tdContentPublishUp'], name='web_tbconte_bConten_b53754_idx'),
        ),
        migrations.AddIndex(
            model_name='tbcontent',
            index=models.Index(fields=['bContentPublish', 'tdContentPublishDown'], name='web_tbconte_bConten_dd200b_idx'),
        ),
    ]
