# Generated by Django 3.2.5 on 2021-07-24 10:17
# C:\PYTHON\ENV\cadpoint2\lib\site-packages\filer\migrations\0013_auto_20210724_1317.py
#     - Alter field id on clipboard
#     - Alter field id on clipboarditem
#     - Alter field id on file
#     - Alter field id on folder
#     - Alter field id on folderpermission
#     - Alter field id on thumbnailoption

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clipboarditem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='folderpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thumbnailoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
